### ISSUE TITLE
UI: Make it clear which tab is selected in QR library

### ISSUE THREAD

**Issue by nic3-14159** [CMPUT301W23T40/CaptureTheQR#103]
Currently, there is no visual feedback to indicate whether "My QRs" or "All QRs" is selected

My QRs:
![Screenshot_20230318_144149](https://user-images.githubusercontent.com/26641941/226138900-7aa8bc68-d951-436b-b36b-9908d61c530b.png)

All QRs:
![Screenshot_20230318_144204](https://user-images.githubusercontent.com/26641941/226138982-96104abe-c597-4444-ba41-e2736cc92be3.png)

**Comment by AnushkaKhare-Eng** [comment]
will not do
