### ISSUE TITLE
write a script of what actions we want to demo and test

### ISSUE THREAD

**Issue by real-rookie** [CMPUT301W23T40/CaptureTheQR#130]

**Comment by ekhumbata** [comment]
### Intro: team 40, CaptureTheQR, demo wizards, made this app for a fun way to connect with friends and promote exercise and exploring your local area! 

1. Start App - **Eric Speaking**
   1. Note total score and number of codes
   2. Note high and low scores - click to show info

2. Show Map - **Eric Speaking**
   1. Show the code we will scan DNE in CSC
   2. Click localization button, map will snap to CSC

4. Show QR library - **Eric Speaking**
   1. Show the code we will scan DNE

5. Scan a QR - **Kevin Speaking**
   1. Add a comment
   3. Add a picture
   4. Add the location
   5. Submit
   6. Note that the main page numbers have changed 


8. Go to QR library  - **Zhiwen Speaking**
   1. Show new code in My QRs
   2. Click on new code
   4. We can see the name, scores, location, image.
   5. And we can also comment on it

 9. Library 2   - **Rachel Speaking**
    1. Delete a different code - NOT THE ONE WE JUST SCANNED OR **cool GloMoMega**
    2. Verbally say *the code still exists for others if they are not the last one*
    3. Go to all QR's (specifically codes that do not exist for the logged in user)
    4. Click on a code from the QR library
    6. Like the code, show you can only like once 
    8. Go back to the library main page
    9. Attempt to delete that code - this should fail due to security permissions


11. Go to Map - **Nic Speaking**
    1. Click on the QR code to show the info on the new code in CSC
    2. Show different QR locations on map (zoom out)
    3. Enter sherwood park on map search and show code in sherwood park


12. Go to Scoreboard - **Anushka Speaking**
    1. Show scrolling on sort by "highest QR score"
    2. Click on a user in the scoreboard to show user info
    3. Show change in scoreboard and scrolling after sort by "highest number of QR codes"
    5. Show user name search (exact match)
    6. Show a user name search with no match
    7. Brute force scoring algorithm
