### ISSUE TITLE
Add a toast to identify the device for each player

### ISSUE THREAD

**Issue by AnushkaKhare-Eng** [CMPUT301W23T40/CaptureTheQR#66]
This is just a nice to have, if we have time. We can add a toast to tell the user that we have identified the device. 
"Welcome back playername"

**Comment by AnushkaKhare-Eng** [comment]
Related to US  04.02.01

**Comment by ekhumbata** [comment]
the main activity should already show welcome `username`. This is a redundant ticket, closing. (blame Rachel too not just me xD)
